name: CartEssentials
main: me.FluffyWolfers.CE.CE
version: 1.0
commands:
  cartessentials:
    description: Main command for ChestRegeneration plugin
    permission: cartessentials.ce
    permission-message: No no no!
    aliases: [cart, essentials, cartessentials, ce]
permissions:
  cartessentials.ce:
    default: true
  cartessentials.reload:
    default: op
  cartessentials.fly:
    default: true
  cartessentials.stationary:
    default: true
  cartessentials.jump:
    default: true
  cartessentials.effects.speed:
    default: true
  cartessentials.effects.break:
    default: true
  cartessentials.effects.stop:
    default: true
  cartessentials.effects.reverse:
    default: true
  cartessentials.effects.*:
    children:
      cartessentials.effects.speed: true
      cartessentials.effects.break: true
      cartessentials.effects.stop: true
      cartessentials.effects.reverse: true